### ISSUE TITLE
allocation failure in bmp_getinfo

### ISSUE THREAD

**Issue by bestshow** [mdadams/jasper#148]
On 2.0.12

```
./imginfo -f $FILE
==24569==ERROR: failed to allocate 0x606063000 (25870872576) bytes of LargeMmapAllocator (error code: 12)
==24569==Process memory map follows:
    0x000000400000-0x000000548000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000748000-0x000000749000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000749000-0x00000074d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x00000074d000-0x0000013b3000
    0x00007fff7000-0x00008fff7000
    0x00008fff7000-0x02008fff7000
    0x02008fff7000-0x10007fff8000
    0x600000000000-0x602000000000
    0x602000000000-0x602000010000
    0x602000010000-0x602e00000000
    0x602e00000000-0x602e00010000
    0x602e00010000-0x603000000000
    0x603000000000-0x603000010000
    0x603000010000-0x603e00000000
    0x603e00000000-0x603e00010000
    0x603e00010000-0x604000000000
    0x604000000000-0x604000010000
    0x604000010000-0x604e00000000
    0x604e00000000-0x604e00010000
    0x604e00010000-0x606000000000
    0x606000000000-0x606000010000
    0x606000010000-0x606e00000000
    0x606e00000000-0x606e00010000
    0x606e00010000-0x60b000000000
    0x60b000000000-0x60b000010000
    0x60b000010000-0x60be00000000
    0x60be00000000-0x60be00010000
    0x60be00010000-0x624000000000
    0x624000000000-0x624000010000
    0x624000010000-0x624e00000000
    0x624e00000000-0x624e00010000
    0x624e00010000-0x625000000000
    0x625000000000-0x625000010000
    0x625000010000-0x625e00000000
    0x625e00000000-0x625e00010000
    0x625e00010000-0x640000000000
    0x640000000000-0x640000003000
    0x7febb5d00000-0x7febb5e00000
    0x7febb5f00000-0x7febb6000000
    0x7febb6100000-0x7febb6200000
    0x7febb6300000-0x7febb6400000
    0x7febb649e000-0x7febb87f0000
    0x7febb87f0000-0x7febb89a6000    /usr/lib64/libc-2.17.so
    0x7febb89a6000-0x7febb8ba6000    /usr/lib64/libc-2.17.so
    0x7febb8ba6000-0x7febb8baa000    /usr/lib64/libc-2.17.so
    0x7febb8baa000-0x7febb8bac000    /usr/lib64/libc-2.17.so
    0x7febb8bac000-0x7febb8bb1000
    0x7febb8bb1000-0x7febb8bc6000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7febb8bc6000-0x7febb8dc5000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7febb8dc5000-0x7febb8dc6000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7febb8dc6000-0x7febb8dc7000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7febb8dc7000-0x7febb8dc9000    /usr/lib64/libdl-2.17.so
    0x7febb8dc9000-0x7febb8fc9000    /usr/lib64/libdl-2.17.so
    0x7febb8fc9000-0x7febb8fca000    /usr/lib64/libdl-2.17.so
    0x7febb8fca000-0x7febb8fcb000    /usr/lib64/libdl-2.17.so
    0x7febb8fcb000-0x7febb8fd2000    /usr/lib64/librt-2.17.so
    0x7febb8fd2000-0x7febb91d1000    /usr/lib64/librt-2.17.so
    0x7febb91d1000-0x7febb91d2000    /usr/lib64/librt-2.17.so
    0x7febb91d2000-0x7febb91d3000    /usr/lib64/librt-2.17.so
    0x7febb91d3000-0x7febb91ea000    /usr/lib64/libpthread-2.17.so
    0x7febb91ea000-0x7febb93e9000    /usr/lib64/libpthread-2.17.so
    0x7febb93e9000-0x7febb93ea000    /usr/lib64/libpthread-2.17.so
    0x7febb93ea000-0x7febb93eb000    /usr/lib64/libpthread-2.17.so
    0x7febb93eb000-0x7febb93ef000
    0x7febb93ef000-0x7febb94ef000    /usr/lib64/libm-2.17.so
    0x7febb94ef000-0x7febb96ef000    /usr/lib64/libm-2.17.so
    0x7febb96ef000-0x7febb96f0000    /usr/lib64/libm-2.17.so
    0x7febb96f0000-0x7febb96f1000    /usr/lib64/libm-2.17.so
    0x7febb96f1000-0x7febb972a000    /usr/lib64/libjpeg.so.9.2.0
    0x7febb972a000-0x7febb992a000    /usr/lib64/libjpeg.so.9.2.0
    0x7febb992a000-0x7febb992b000    /usr/lib64/libjpeg.so.9.2.0
    0x7febb992b000-0x7febb992c000    /usr/lib64/libjpeg.so.9.2.0
    0x7febb992c000-0x7febb9b99000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7febb9b99000-0x7febb9d98000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7febb9d98000-0x7febb9d9d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7febb9d9d000-0x7febb9db1000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7febb9db1000-0x7febb9db9000
    0x7febb9db9000-0x7febb9dd9000    /usr/lib64/ld-2.17.so
    0x7febb9e50000-0x7febb9fbd000
    0x7febb9fbd000-0x7febb9fd8000
    0x7febb9fd8000-0x7febb9fd9000    /usr/lib64/ld-2.17.so
    0x7febb9fd9000-0x7febb9fda000    /usr/lib64/ld-2.17.so
    0x7febb9fda000-0x7febb9fdb000
    0x7ffd16671000-0x7ffd16692000    [stack]
    0x7ffd1670d000-0x7ffd1670f000    [vdso]
    0xffffffffff600000-0xffffffffff601000    [vsyscall]
==24569==End of process memory map.
==24569== CHECK failed: /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x4ea5df in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x501f05 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f2ba0 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x4fb37e in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x42662f in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x42662f in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x42662f in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x4dffa9 in malloc /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #8 0x7febb99d1e33 in jas_malloc /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:241:11
    #9 0x7febb99d1e33 in jas_alloc2 /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:274
    #10 0x7febb99f2bc5 in bmp_getinfo /home/ test/Downloads/jasper/jasper-master/src/libjasper/bmp/bmp_dec.c:399:25
    #11 0x7febb99f2bc5 in bmp_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/bmp/bmp_dec.c:187
    #12 0x7febb99bed40 in jas_image_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:442:16
    #13 0x51603e in main /home/ test/Downloads/jasper/jasper-master/src/appl/imginfo.c:238:16
    #14 0x7febb8811b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
    #15 0x41b01b in _start (/home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo+0x41b01b)

```
testcase:https://github.com/bestshow/p0cs/blob/master/allocation_failure_in_bmp_getinfo_399
Credit : ADLab of Venustech

**Comment by asarubbo** [comment]
see #35

**Comment by mdadams** [comment]
As noted by @asarubbo, please see #35.  This is not really a bug in JasPer.  ASan is failing because you are running out of memory, which is not the fault of JasPer, per se.
