### ISSUE TITLE
allocation failure in jas_stream_memopen2

### ISSUE THREAD

**Issue by bestshow** [mdadams/jasper#149]
On 2.0.12

```
./imginfo -f $FILE
==105460==ERROR: failed to allocate 0xcefa26000 (55560003584) bytes of LargeMmapAllocator (error code: 12)
==105460==Process memory map follows:
    0x000000400000-0x000000548000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000748000-0x000000749000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000749000-0x00000074d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x00000074d000-0x0000013b3000   
    0x00007fff7000-0x00008fff7000   
    0x00008fff7000-0x02008fff7000   
    0x02008fff7000-0x10007fff8000   
    0x600000000000-0x602000000000   
    0x602000000000-0x602000010000   
    0x602000010000-0x602e00000000   
    0x602e00000000-0x602e00010000   
    0x602e00010000-0x603000000000   
    0x603000000000-0x603000010000   
    0x603000010000-0x603e00000000   
    0x603e00000000-0x603e00010000   
    0x603e00010000-0x604000000000   
    0x604000000000-0x604000010000   
    0x604000010000-0x604e00000000   
    0x604e00000000-0x604e00010000   
    0x604e00010000-0x606000000000   
    0x606000000000-0x606000010000   
    0x606000010000-0x606e00000000   
    0x606e00000000-0x606e00010000   
    0x606e00010000-0x607000000000   
    0x607000000000-0x607000010000   
    0x607000010000-0x607e00000000   
    0x607e00000000-0x607e00010000   
    0x607e00010000-0x60b000000000   
    0x60b000000000-0x60b000010000   
    0x60b000010000-0x60be00000000   
    0x60be00000000-0x60be00010000   
    0x60be00010000-0x619000000000   
    0x619000000000-0x619000010000   
    0x619000010000-0x619e00000000   
    0x619e00000000-0x619e00010000   
    0x619e00010000-0x624000000000   
    0x624000000000-0x624000010000   
    0x624000010000-0x624e00000000   
    0x624e00000000-0x624e00010000   
    0x624e00010000-0x625000000000   
    0x625000000000-0x625000010000   
    0x625000010000-0x625e00000000   
    0x625e00000000-0x625e00010000   
    0x625e00010000-0x640000000000   
    0x640000000000-0x640000003000   
    0x7f5f03000000-0x7f5f03100000   
    0x7f5f03200000-0x7f5f03300000   
    0x7f5f03400000-0x7f5f03500000   
    0x7f5f03600000-0x7f5f03700000   
    0x7f5f0375d000-0x7f5f05aaf000   
    0x7f5f05aaf000-0x7f5f05c65000    /usr/lib64/libc-2.17.so
    0x7f5f05c65000-0x7f5f05e65000    /usr/lib64/libc-2.17.so
    0x7f5f05e65000-0x7f5f05e69000    /usr/lib64/libc-2.17.so
    0x7f5f05e69000-0x7f5f05e6b000    /usr/lib64/libc-2.17.so
    0x7f5f05e6b000-0x7f5f05e70000   
    0x7f5f05e70000-0x7f5f05e85000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f5f05e85000-0x7f5f06084000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f5f06084000-0x7f5f06085000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f5f06085000-0x7f5f06086000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f5f06086000-0x7f5f06088000    /usr/lib64/libdl-2.17.so
    0x7f5f06088000-0x7f5f06288000    /usr/lib64/libdl-2.17.so
    0x7f5f06288000-0x7f5f06289000    /usr/lib64/libdl-2.17.so
    0x7f5f06289000-0x7f5f0628a000    /usr/lib64/libdl-2.17.so
    0x7f5f0628a000-0x7f5f06291000    /usr/lib64/librt-2.17.so
    0x7f5f06291000-0x7f5f06490000    /usr/lib64/librt-2.17.so
    0x7f5f06490000-0x7f5f06491000    /usr/lib64/librt-2.17.so
    0x7f5f06491000-0x7f5f06492000    /usr/lib64/librt-2.17.so
    0x7f5f06492000-0x7f5f064a9000    /usr/lib64/libpthread-2.17.so
    0x7f5f064a9000-0x7f5f066a8000    /usr/lib64/libpthread-2.17.so
    0x7f5f066a8000-0x7f5f066a9000    /usr/lib64/libpthread-2.17.so
    0x7f5f066a9000-0x7f5f066aa000    /usr/lib64/libpthread-2.17.so
    0x7f5f066aa000-0x7f5f066ae000   
    0x7f5f066ae000-0x7f5f067ae000    /usr/lib64/libm-2.17.so
    0x7f5f067ae000-0x7f5f069ae000    /usr/lib64/libm-2.17.so
    0x7f5f069ae000-0x7f5f069af000    /usr/lib64/libm-2.17.so
    0x7f5f069af000-0x7f5f069b0000    /usr/lib64/libm-2.17.so
    0x7f5f069b0000-0x7f5f069e9000    /usr/lib64/libjpeg.so.9.2.0
    0x7f5f069e9000-0x7f5f06be9000    /usr/lib64/libjpeg.so.9.2.0
    0x7f5f06be9000-0x7f5f06bea000    /usr/lib64/libjpeg.so.9.2.0
    0x7f5f06bea000-0x7f5f06beb000    /usr/lib64/libjpeg.so.9.2.0
    0x7f5f06beb000-0x7f5f06e58000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f5f06e58000-0x7f5f07057000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f5f07057000-0x7f5f0705c000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f5f0705c000-0x7f5f07070000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f5f07070000-0x7f5f07078000   
    0x7f5f07078000-0x7f5f07098000    /usr/lib64/ld-2.17.so
    0x7f5f0710f000-0x7f5f0727c000   
    0x7f5f0727c000-0x7f5f07297000   
    0x7f5f07297000-0x7f5f07298000    /usr/lib64/ld-2.17.so
    0x7f5f07298000-0x7f5f07299000    /usr/lib64/ld-2.17.so
    0x7f5f07299000-0x7f5f0729a000   
    0x7fff7092e000-0x7fff7094f000    [stack]
    0x7fff709b3000-0x7fff709b5000    [vdso]
    0xffffffffff600000-0xffffffffff601000    [vsyscall]
==105460==End of process memory map.
==105460== CHECK failed: /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x4ea5df in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x501f05 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f2ba0 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x4fb37e in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x42662f in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x42662f in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x42662f in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x4dffa9 in malloc /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #8 0x7f5f06c90b51 in jas_malloc /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:241:11
    #9 0x7f5f06c9a030 in jas_stream_memopen2 /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_stream.c:311:15
    #10 0x7f5f06c7aa8d in jas_image_cmpt_create /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:381:28
    #11 0x7f5f06c83334 in jas_image_addcmpt /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:781:18
    #12 0x7f5f06e21e40 in pgx_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/pgx/pgx_dec.c:200:6
    #13 0x7f5f06c7dd40 in jas_image_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:442:16
    #14 0x51603e in main /home/ test/Downloads/jasper/jasper-master/src/appl/imginfo.c:238:16
    #15 0x7f5f05ad0b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
    #16 0x41b01b in _start (/home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo+0x41b01b)

```
testcase:https://github.com/bestshow/p0cs/blob/master/allocation_failure_in_jas_stream_memopen2_311
Credit : ADLab of Venustech

**Comment by mdadams** [comment]
This is not a bug in JasPer.  ASan is failing because the memory request cannot be satisfied.  This is not the fault of JasPer.  See issue #35 (which is a similar issue).
