### ISSUE TITLE
allocation failure in jas_matrix_create

### ISSUE THREAD

**Issue by bestshow** [mdadams/jasper#150]
On 2.0.12

```
./imginfo -f $FILE
==112069==ERROR: failed to allocate 0x3e16929000 (266666676224) bytes of LargeMmapAllocator (error code: 12)
==112069==Process memory map follows:
    0x000000400000-0x000000548000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000748000-0x000000749000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000749000-0x00000074d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x00000074d000-0x0000013b3000   
    0x00007fff7000-0x00008fff7000   
    0x00008fff7000-0x02008fff7000   
    0x02008fff7000-0x10007fff8000   
    0x600000000000-0x602000000000   
    0x602000000000-0x602000010000   
    0x602000010000-0x602e00000000   
    0x602e00000000-0x602e00010000   
    0x602e00010000-0x603000000000   
    0x603000000000-0x603000010000   
    0x603000010000-0x603e00000000   
    0x603e00000000-0x603e00010000   
    0x603e00010000-0x604000000000   
    0x604000000000-0x604000010000   
    0x604000010000-0x604e00000000   
    0x604e00000000-0x604e00010000   
    0x604e00010000-0x606000000000   
    0x606000000000-0x606000010000   
    0x606000010000-0x606e00000000   
    0x606e00000000-0x606e00010000   
    0x606e00010000-0x607000000000   
    0x607000000000-0x607000010000   
    0x607000010000-0x607e00000000   
    0x607e00000000-0x607e00010000   
    0x607e00010000-0x608000000000   
    0x608000000000-0x608000010000   
    0x608000010000-0x608e00000000   
    0x608e00000000-0x608e00010000   
    0x608e00010000-0x60b000000000   
    0x60b000000000-0x60b000010000   
    0x60b000010000-0x60be00000000   
    0x60be00000000-0x60be00010000   
    0x60be00010000-0x619000000000   
    0x619000000000-0x619000010000   
    0x619000010000-0x619e00000000   
    0x619e00000000-0x619e00010000   
    0x619e00010000-0x624000000000   
    0x624000000000-0x624000010000   
    0x624000010000-0x624e00000000   
    0x624e00000000-0x624e00010000   
    0x624e00010000-0x625000000000   
    0x625000000000-0x625000010000   
    0x625000010000-0x625e00000000   
    0x625e00000000-0x625e00010000   
    0x625e00010000-0x640000000000   
    0x640000000000-0x640000003000   
    0x7f2c0bc00000-0x7f2c0bd00000   
    0x7f2c0be00000-0x7f2c0bf00000   
    0x7f2c0c000000-0x7f2c0c100000   
    0x7f2c0c200000-0x7f2c0c300000   
    0x7f2c0c3e4000-0x7f2c0e736000   
    0x7f2c0e736000-0x7f2c0e8ec000    /usr/lib64/libc-2.17.so
    0x7f2c0e8ec000-0x7f2c0eaec000    /usr/lib64/libc-2.17.so
    0x7f2c0eaec000-0x7f2c0eaf0000    /usr/lib64/libc-2.17.so
    0x7f2c0eaf0000-0x7f2c0eaf2000    /usr/lib64/libc-2.17.so
    0x7f2c0eaf2000-0x7f2c0eaf7000   
    0x7f2c0eaf7000-0x7f2c0eb0c000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f2c0eb0c000-0x7f2c0ed0b000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f2c0ed0b000-0x7f2c0ed0c000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f2c0ed0c000-0x7f2c0ed0d000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7f2c0ed0d000-0x7f2c0ed0f000    /usr/lib64/libdl-2.17.so
    0x7f2c0ed0f000-0x7f2c0ef0f000    /usr/lib64/libdl-2.17.so
    0x7f2c0ef0f000-0x7f2c0ef10000    /usr/lib64/libdl-2.17.so
    0x7f2c0ef10000-0x7f2c0ef11000    /usr/lib64/libdl-2.17.so
    0x7f2c0ef11000-0x7f2c0ef18000    /usr/lib64/librt-2.17.so
    0x7f2c0ef18000-0x7f2c0f117000    /usr/lib64/librt-2.17.so
    0x7f2c0f117000-0x7f2c0f118000    /usr/lib64/librt-2.17.so
    0x7f2c0f118000-0x7f2c0f119000    /usr/lib64/librt-2.17.so
    0x7f2c0f119000-0x7f2c0f130000    /usr/lib64/libpthread-2.17.so
    0x7f2c0f130000-0x7f2c0f32f000    /usr/lib64/libpthread-2.17.so
    0x7f2c0f32f000-0x7f2c0f330000    /usr/lib64/libpthread-2.17.so
    0x7f2c0f330000-0x7f2c0f331000    /usr/lib64/libpthread-2.17.so
    0x7f2c0f331000-0x7f2c0f335000   
    0x7f2c0f335000-0x7f2c0f435000    /usr/lib64/libm-2.17.so
    0x7f2c0f435000-0x7f2c0f635000    /usr/lib64/libm-2.17.so
    0x7f2c0f635000-0x7f2c0f636000    /usr/lib64/libm-2.17.so
    0x7f2c0f636000-0x7f2c0f637000    /usr/lib64/libm-2.17.so
    0x7f2c0f637000-0x7f2c0f670000    /usr/lib64/libjpeg.so.9.2.0
    0x7f2c0f670000-0x7f2c0f870000    /usr/lib64/libjpeg.so.9.2.0
    0x7f2c0f870000-0x7f2c0f871000    /usr/lib64/libjpeg.so.9.2.0
    0x7f2c0f871000-0x7f2c0f872000    /usr/lib64/libjpeg.so.9.2.0
    0x7f2c0f872000-0x7f2c0fadf000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f2c0fadf000-0x7f2c0fcde000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f2c0fcde000-0x7f2c0fce3000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f2c0fce3000-0x7f2c0fcf7000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7f2c0fcf7000-0x7f2c0fcff000   
    0x7f2c0fcff000-0x7f2c0fd1f000    /usr/lib64/ld-2.17.so
    0x7f2c0fd96000-0x7f2c0ff03000   
    0x7f2c0ff03000-0x7f2c0ff1e000   
    0x7f2c0ff1e000-0x7f2c0ff1f000    /usr/lib64/ld-2.17.so
    0x7f2c0ff1f000-0x7f2c0ff20000    /usr/lib64/ld-2.17.so
    0x7f2c0ff20000-0x7f2c0ff21000   
    0x7ffcdeea8000-0x7ffcdeec9000    [stack]
    0x7ffcdefe3000-0x7ffcdefe5000    [vdso]
    0xffffffffff600000-0xffffffffff601000    [vsyscall]
==112069==End of process memory map.
==112069== CHECK failed: /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x4ea5df in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x501f05 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f2ba0 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x4fb37e in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x42662f in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x42662f in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x42662f in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x4dffa9 in malloc /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #8 0x7f2c0f917e33 in jas_malloc /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:241:11
    #9 0x7f2c0f917e33 in jas_alloc2 /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:274
    #10 0x7f2c0f918e33 in jas_matrix_create /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_seq.c:138:25
    #11 0x7f2c0faa8ea5 in pgx_getdata /home/ test/Downloads/jasper/jasper-master/src/libjasper/pgx/pgx_dec.c:325:15
    #12 0x7f2c0faa8ea5 in pgx_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/pgx/pgx_dec.c:203
    #13 0x7f2c0f904d40 in jas_image_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:442:16
    #14 0x51603e in main /home/ test/Downloads/jasper/jasper-master/src/appl/imginfo.c:238:16
    #15 0x7f2c0e757b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
    #16 0x41b01b in _start (/home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo+0x41b01b)
```
testcase:https://github.com/bestshow/p0cs/blob/master/allocation_failure_in_jas_matrix_create_138
Credit : ADLab of Venustech

**Comment by mdadams** [comment]
Unless I am misunderstanding things, this is not a bug in JasPer.  ASan is failing because you are running out of memory.  Please refer to #35 (which is a similar issue.
