### ISSUE TITLE
allocation failure in jpc_dec_process_siz

### ISSUE THREAD

**Issue by bestshow** [mdadams/jasper#151]
On 2.0.12

```
./imginfo -f $FILE
==113377==ERROR: failed to allocate 0x11e0001000 (76772544512) bytes of LargeMmapAllocator (error code: 12)
==113377==Process memory map follows:
    0x000000400000-0x000000548000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000748000-0x000000749000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x000000749000-0x00000074d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo
    0x00000074d000-0x0000013b3000   
    0x00007fff7000-0x00008fff7000   
    0x00008fff7000-0x02008fff7000   
    0x02008fff7000-0x10007fff8000   
    0x600000000000-0x602000000000   
    0x602000000000-0x602000010000   
    0x602000010000-0x602e00000000   
    0x602e00000000-0x602e00010000   
    0x602e00010000-0x603000000000   
    0x603000000000-0x603000010000   
    0x603000010000-0x603e00000000   
    0x603e00000000-0x603e00010000   
    0x603e00010000-0x604000000000   
    0x604000000000-0x604000010000   
    0x604000010000-0x604e00000000   
    0x604e00000000-0x604e00010000   
    0x604e00010000-0x606000000000   
    0x606000000000-0x606000010000   
    0x606000010000-0x606e00000000   
    0x606e00000000-0x606e00010000   
    0x606e00010000-0x60b000000000   
    0x60b000000000-0x60b000010000   
    0x60b000010000-0x60be00000000   
    0x60be00000000-0x60be00010000   
    0x60be00010000-0x60d000000000   
    0x60d000000000-0x60d000010000   
    0x60d000010000-0x60de00000000   
    0x60de00000000-0x60de00010000   
    0x60de00010000-0x611000000000   
    0x611000000000-0x611000010000   
    0x611000010000-0x611e00000000   
    0x611e00000000-0x611e00010000   
    0x611e00010000-0x618000000000   
    0x618000000000-0x618000010000   
    0x618000010000-0x618e00000000   
    0x618e00000000-0x618e00010000   
    0x618e00010000-0x619000000000   
    0x619000000000-0x619000010000   
    0x619000010000-0x619e00000000   
    0x619e00000000-0x619e00010000   
    0x619e00010000-0x624000000000   
    0x624000000000-0x624000010000   
    0x624000010000-0x624e00000000   
    0x624e00000000-0x624e00010000   
    0x624e00010000-0x625000000000   
    0x625000000000-0x625000010000   
    0x625000010000-0x625e00000000   
    0x625e00000000-0x625e00010000   
    0x625e00010000-0x640000000000   
    0x640000000000-0x640000003000   
    0x7fbfe8300000-0x7fbfe8400000   
    0x7fbfe8500000-0x7fbfe8600000   
    0x7fbfe8700000-0x7fbfe8800000   
    0x7fbfe8900000-0x7fbfe8a00000   
    0x7fbfe8a4e000-0x7fbfeada0000   
    0x7fbfeada0000-0x7fbfeaf56000    /usr/lib64/libc-2.17.so
    0x7fbfeaf56000-0x7fbfeb156000    /usr/lib64/libc-2.17.so
    0x7fbfeb156000-0x7fbfeb15a000    /usr/lib64/libc-2.17.so
    0x7fbfeb15a000-0x7fbfeb15c000    /usr/lib64/libc-2.17.so
    0x7fbfeb15c000-0x7fbfeb161000   
    0x7fbfeb161000-0x7fbfeb176000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fbfeb176000-0x7fbfeb375000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fbfeb375000-0x7fbfeb376000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fbfeb376000-0x7fbfeb377000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fbfeb377000-0x7fbfeb379000    /usr/lib64/libdl-2.17.so
    0x7fbfeb379000-0x7fbfeb579000    /usr/lib64/libdl-2.17.so
    0x7fbfeb579000-0x7fbfeb57a000    /usr/lib64/libdl-2.17.so
    0x7fbfeb57a000-0x7fbfeb57b000    /usr/lib64/libdl-2.17.so
    0x7fbfeb57b000-0x7fbfeb582000    /usr/lib64/librt-2.17.so
    0x7fbfeb582000-0x7fbfeb781000    /usr/lib64/librt-2.17.so
    0x7fbfeb781000-0x7fbfeb782000    /usr/lib64/librt-2.17.so
    0x7fbfeb782000-0x7fbfeb783000    /usr/lib64/librt-2.17.so
    0x7fbfeb783000-0x7fbfeb79a000    /usr/lib64/libpthread-2.17.so
    0x7fbfeb79a000-0x7fbfeb999000    /usr/lib64/libpthread-2.17.so
    0x7fbfeb999000-0x7fbfeb99a000    /usr/lib64/libpthread-2.17.so
    0x7fbfeb99a000-0x7fbfeb99b000    /usr/lib64/libpthread-2.17.so
    0x7fbfeb99b000-0x7fbfeb99f000   
    0x7fbfeb99f000-0x7fbfeba9f000    /usr/lib64/libm-2.17.so
    0x7fbfeba9f000-0x7fbfebc9f000    /usr/lib64/libm-2.17.so
    0x7fbfebc9f000-0x7fbfebca0000    /usr/lib64/libm-2.17.so
    0x7fbfebca0000-0x7fbfebca1000    /usr/lib64/libm-2.17.so
    0x7fbfebca1000-0x7fbfebcda000    /usr/lib64/libjpeg.so.9.2.0
    0x7fbfebcda000-0x7fbfebeda000    /usr/lib64/libjpeg.so.9.2.0
    0x7fbfebeda000-0x7fbfebedb000    /usr/lib64/libjpeg.so.9.2.0
    0x7fbfebedb000-0x7fbfebedc000    /usr/lib64/libjpeg.so.9.2.0
    0x7fbfebedc000-0x7fbfec149000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7fbfec149000-0x7fbfec348000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7fbfec348000-0x7fbfec34d000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7fbfec34d000-0x7fbfec361000    /home/ test/Downloads/jasper/jasper-master/jasperbuild/src/libjasper/libjasper.so.4.0.0
    0x7fbfec361000-0x7fbfec369000   
    0x7fbfec369000-0x7fbfec389000    /usr/lib64/ld-2.17.so
    0x7fbfec400000-0x7fbfec56d000   
    0x7fbfec56d000-0x7fbfec588000   
    0x7fbfec588000-0x7fbfec589000    /usr/lib64/ld-2.17.so
    0x7fbfec589000-0x7fbfec58a000    /usr/lib64/ld-2.17.so
    0x7fbfec58a000-0x7fbfec58b000   
    0x7ffea5a70000-0x7ffea5a91000    [stack]
    0x7ffea5b97000-0x7ffea5b99000    [vdso]
    0xffffffffff600000-0xffffffffff601000    [vsyscall]
==113377==End of process memory map.
==113377== CHECK failed: /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x4ea5df in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x501f05 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f2ba0 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x4fb37e in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x42662f in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x42662f in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x42662f in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x4dffa9 in malloc /home/ test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #8 0x7fbfebf81e33 in jas_malloc /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:241:11
    #9 0x7fbfebf81e33 in jas_alloc2 /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_malloc.c:274
    #10 0x7fbfec00416b in jpc_dec_process_siz /home/ test/Downloads/jasper/jasper-master/src/libjasper/jpc/jpc_dec.c:1305:21
    #11 0x7fbfec010e17 in jpc_dec_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/jpc/jpc_dec.c:424:10
    #12 0x7fbfec010e17 in jpc_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/jpc/jpc_dec.c:261
    #13 0x7fbfebf6ed40 in jas_image_decode /home/ test/Downloads/jasper/jasper-master/src/libjasper/base/jas_image.c:442:16
    #14 0x51603e in main /home/ test/Downloads/jasper/jasper-master/src/appl/imginfo.c:238:16
    #15 0x7fbfeadc1b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
    #16 0x41b01b in _start (/home/ test/Downloads/jasper/jasper-master/jasperbuild/src/appl/imginfo+0x41b01b)
```

testcase:https://github.com/bestshow/p0cs/blob/master/allocation_failure_in_jpc_dec_process_siz_1305
Credit : ADLab of Venustech

**Comment by mdadams** [comment]
Again, as in #148, unless I am misunderstanding, this is not a bug in JasPer.  ASan will fail if a memory request cannot be satisfied.  This is not a bug in JasPer per se.   If you want JasPer to refuse to decode huge images, set the maximum allowable image size (for decoding) to be smaller.
