### ISSUE TITLE
segfault / null pointer access in imginfo on malformed mif

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#41]
This malformed mif file will segfault imginfo. Found with afl.
[nullptr.zip](https://github.com/mdadams/jasper/files/543245/nullptr.zip)

Stack trace:
```
==5092==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004f244a bp 0x60700000dfb0 sp 0x7ffe0d1dfbb0 T0)
    #0 0x4f2449 in main /f/jasper/jasper/src/appl/imginfo.c:198:10
    #1 0x7f2d67e4078f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #2 0x4195d8 in _start (/r/jasper/imginfo+0x4195d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /f/jasper/jasper/src/appl/imginfo.c:198:10 in main
==5092==ABORTING

**Comment by mdadams** [comment]
This is now fixed. See commit d743f7e0ad901dc3419fc1042939a5454de96c16.
